"""数据库表结构版本定义"""

SCHEMA_VERSIONS = {
    1: {
        "description": "初始版本 - 基础表结构",
        "changes": {
            "new_tables": [
                "accounts",
                "portfolios",
                "fund_transactions",
                "fund_positions",
                "fund_nav_history",
            ],
            "alter_tables": {},
            "drop_tables": [],
        },
        "schema": {
            "accounts": {
                "fields": {
                    "id": "VARCHAR(255) NOT NULL PRIMARY KEY",
                    "created_at": "DATETIME NOT NULL",
                    "updated_at": "DATETIME NOT NULL",
                    "name": "VARCHAR(255) NOT NULL",
                    "description": "VARCHAR(255)",
                }
            },
            "portfolios": {
                "fields": {
                    "id": "VARCHAR(255) NOT NULL PRIMARY KEY",
                    "created_at": "DATETIME NOT NULL",
                    "updated_at": "DATETIME NOT NULL",
                    "account_id": "VARCHAR(255) NOT NULL",
                    "name": "VARCHAR(255) NOT NULL",
                    "description": "VARCHAR(255)",
                    "is_default": "INTEGER NOT NULL",
                },
                "foreign_keys": {"account_id": "accounts(id)"},
                "indexes": ["account_id"],
            },
            "fund_transactions": {
                "fields": {
                    "id": "VARCHAR(255) NOT NULL PRIMARY KEY",
                    "created_at": "DATETIME NOT NULL",
                    "updated_at": "DATETIME NOT NULL",
                    "portfolio_id": "VARCHAR(255) NOT NULL",
                    "code": "VARCHAR(10) NOT NULL",
                    "type": "VARCHAR(20) NOT NULL",
                    "shares": "DECIMAL(20, 4) NOT NULL",
                    "amount": "DECIMAL(20, 2) NOT NULL",
                    "nav": "DECIMAL(10, 4) NOT NULL",
                    "fee": "DECIMAL(10, 2) NOT NULL",
                    "transaction_date": "DATETIME NOT NULL",
                },
                "foreign_keys": {"portfolio_id": "portfolios(id)"},
                "indexes": ["portfolio_id", "code"],
            },
            "fund_positions": {
                "fields": {
                    "id": "VARCHAR(255) NOT NULL PRIMARY KEY",
                    "created_at": "DATETIME NOT NULL",
                    "updated_at": "DATETIME NOT NULL",
                    "portfolio_id": "VARCHAR(255) NOT NULL",
                    "code": "VARCHAR(10) NOT NULL",
                    "name": "VARCHAR(50) NOT NULL",
                    "shares": "DECIMAL(20, 4) NOT NULL",
                    "nav": "DECIMAL(10, 4) NOT NULL",
                    "market_value": "DECIMAL(20, 2) NOT NULL",
                    "cost": "DECIMAL(20, 2) NOT NULL",
                    "return_rate": "DECIMAL(10, 4) NOT NULL",
                    "type": "VARCHAR(20) NOT NULL",
                    "purchase_date": "DATETIME NOT NULL",
                },
                "foreign_keys": {"portfolio_id": "portfolios(id)"},
                "indexes": ["portfolio_id", "code"],
            },
            "fund_nav_history": {
                "fields": {
                    "created_at": "DATETIME NOT NULL",
                    "updated_at": "DATETIME NOT NULL",
                    "code": "VARCHAR(10) NOT NULL",
                    "nav_date": "DATETIME NOT NULL",
                    "nav": "DECIMAL(10, 4) NOT NULL",
                    "acc_nav": "DECIMAL(10, 4) NOT NULL",
                    "daily_return": "DECIMAL(10, 4) NOT NULL",
                    "dividend": "DECIMAL(10, 4)",
                },
                "primary_key": ["code", "nav_date"],
                "indexes": ["code"],
            },
        },
    },
    2: {
        "description": "添加基金信息表，重构基金相关表的外键关系",
        "changes": {
            "new_tables": ["funds"],
            "alter_tables": {
                "fund_transactions": {"add_foreign_keys": {"code": "funds(code)"}},
                "fund_positions": {
                    "drop_columns": ["name", "type"],
                    "add_foreign_keys": {"code": "funds(code)"},
                },
                "fund_nav_history": {"add_foreign_keys": {"code": "funds(code)"}},
            },
            "drop_tables": [],
        },
        "schema": {
            "accounts": {
                "fields": {
                    "id": "VARCHAR(255) NOT NULL PRIMARY KEY",
                    "created_at": "DATETIME NOT NULL",
                    "updated_at": "DATETIME NOT NULL",
                    "name": "VARCHAR(255) NOT NULL",
                    "description": "VARCHAR(255)",
                }
            },
            "portfolios": {
                "fields": {
                    "id": "VARCHAR(255) NOT NULL PRIMARY KEY",
                    "created_at": "DATETIME NOT NULL",
                    "updated_at": "DATETIME NOT NULL",
                    "account_id": "VARCHAR(255) NOT NULL",
                    "name": "VARCHAR(255) NOT NULL",
                    "description": "VARCHAR(255)",
                    "is_default": "INTEGER NOT NULL",
                },
                "foreign_keys": {"account_id": "accounts(id)"},
                "indexes": ["account_id"],
            },
            "funds": {
                "fields": {
                    "code": "VARCHAR(10) NOT NULL PRIMARY KEY",
                    "name": "VARCHAR(100) NOT NULL",
                    "type": "VARCHAR(20) NOT NULL",
                    "company": "VARCHAR(100) NOT NULL",
                    "description": "VARCHAR(500)",
                    "created_at": "DATETIME NOT NULL",
                    "updated_at": "DATETIME NOT NULL",
                }
            },
            "fund_transactions": {
                "fields": {
                    "id": "VARCHAR(255) NOT NULL PRIMARY KEY",
                    "created_at": "DATETIME NOT NULL",
                    "updated_at": "DATETIME NOT NULL",
                    "portfolio_id": "VARCHAR(255) NOT NULL",
                    "code": "VARCHAR(10) NOT NULL",
                    "type": "VARCHAR(20) NOT NULL",
                    "shares": "DECIMAL(20, 4) NOT NULL",
                    "amount": "DECIMAL(20, 2) NOT NULL",
                    "nav": "DECIMAL(10, 4) NOT NULL",
                    "fee": "DECIMAL(10, 2) NOT NULL",
                    "transaction_date": "DATETIME NOT NULL",
                },
                "foreign_keys": {
                    "portfolio_id": "portfolios(id)",
                    "code": "funds(code)",
                },
                "indexes": ["portfolio_id", "code"],
            },
            "fund_positions": {
                "fields": {
                    "id": "VARCHAR(255) NOT NULL PRIMARY KEY",
                    "created_at": "DATETIME NOT NULL",
                    "updated_at": "DATETIME NOT NULL",
                    "portfolio_id": "VARCHAR(255) NOT NULL",
                    "code": "VARCHAR(10) NOT NULL",
                    "shares": "DECIMAL(20, 4) NOT NULL",
                    "nav": "DECIMAL(10, 4) NOT NULL",
                    "market_value": "DECIMAL(20, 2) NOT NULL",
                    "cost": "DECIMAL(20, 2) NOT NULL",
                    "return_rate": "DECIMAL(10, 4) NOT NULL",
                    "purchase_date": "DATETIME NOT NULL",
                },
                "foreign_keys": {
                    "portfolio_id": "portfolios(id)",
                    "code": "funds(code)",
                },
                "indexes": ["portfolio_id", "code"],
            },
            "fund_nav_history": {
                "fields": {
                    "created_at": "DATETIME NOT NULL",
                    "updated_at": "DATETIME NOT NULL",
                    "code": "VARCHAR(10) NOT NULL",
                    "nav_date": "DATETIME NOT NULL",
                    "nav": "DECIMAL(10, 4) NOT NULL",
                    "acc_nav": "DECIMAL(10, 4) NOT NULL",
                    "daily_return": "DECIMAL(10, 4) NOT NULL",
                    "dividend": "DECIMAL(10, 4)",
                },
                "primary_key": ["code", "nav_date"],
                "foreign_keys": {"code": "funds(code)"},
                "indexes": ["code"],
            },
        },
    },
    3: {
        "description": "添加任务历史记录表",
        "changes": {
            "new_tables": ["task_history"],
            "alter_tables": {},
            "drop_tables": [],
        },
        "schema": {
            "accounts": {
                "fields": {
                    "id": "VARCHAR(255) NOT NULL PRIMARY KEY",
                    "created_at": "DATETIME NOT NULL",
                    "updated_at": "DATETIME NOT NULL",
                    "name": "VARCHAR(255) NOT NULL",
                    "description": "VARCHAR(255)",
                }
            },
            "portfolios": {
                "fields": {
                    "id": "VARCHAR(255) NOT NULL PRIMARY KEY",
                    "created_at": "DATETIME NOT NULL",
                    "updated_at": "DATETIME NOT NULL",
                    "account_id": "VARCHAR(255) NOT NULL",
                    "name": "VARCHAR(255) NOT NULL",
                    "description": "VARCHAR(255)",
                    "is_default": "INTEGER NOT NULL",
                },
                "foreign_keys": {"account_id": "accounts(id)"},
                "indexes": ["account_id"],
            },
            "funds": {
                "fields": {
                    "code": "VARCHAR(10) NOT NULL PRIMARY KEY",
                    "name": "VARCHAR(100) NOT NULL",
                    "type": "VARCHAR(20) NOT NULL",
                    "company": "VARCHAR(100) NOT NULL",
                    "description": "VARCHAR(500)",
                    "created_at": "DATETIME NOT NULL",
                    "updated_at": "DATETIME NOT NULL",
                }
            },
            "fund_transactions": {
                "fields": {
                    "id": "VARCHAR(255) NOT NULL PRIMARY KEY",
                    "created_at": "DATETIME NOT NULL",
                    "updated_at": "DATETIME NOT NULL",
                    "portfolio_id": "VARCHAR(255) NOT NULL",
                    "code": "VARCHAR(10) NOT NULL",
                    "type": "VARCHAR(20) NOT NULL",
                    "shares": "DECIMAL(20, 4) NOT NULL",
                    "amount": "DECIMAL(20, 2) NOT NULL",
                    "nav": "DECIMAL(10, 4) NOT NULL",
                    "fee": "DECIMAL(10, 2) NOT NULL",
                    "transaction_date": "DATETIME NOT NULL",
                },
                "foreign_keys": {
                    "portfolio_id": "portfolios(id)",
                    "code": "funds(code)",
                },
                "indexes": ["portfolio_id", "code"],
            },
            "fund_positions": {
                "fields": {
                    "id": "VARCHAR(255) NOT NULL PRIMARY KEY",
                    "created_at": "DATETIME NOT NULL",
                    "updated_at": "DATETIME NOT NULL",
                    "portfolio_id": "VARCHAR(255) NOT NULL",
                    "code": "VARCHAR(10) NOT NULL",
                    "shares": "DECIMAL(20, 4) NOT NULL",
                    "nav": "DECIMAL(10, 4) NOT NULL",
                    "market_value": "DECIMAL(20, 2) NOT NULL",
                    "cost": "DECIMAL(20, 2) NOT NULL",
                    "return_rate": "DECIMAL(10, 4) NOT NULL",
                    "purchase_date": "DATETIME NOT NULL",
                },
                "foreign_keys": {
                    "portfolio_id": "portfolios(id)",
                    "code": "funds(code)",
                },
                "indexes": ["portfolio_id", "code"],
            },
            "fund_nav_history": {
                "fields": {
                    "created_at": "DATETIME NOT NULL",
                    "updated_at": "DATETIME NOT NULL",
                    "code": "VARCHAR(10) NOT NULL",
                    "nav_date": "DATETIME NOT NULL",
                    "nav": "DECIMAL(10, 4) NOT NULL",
                    "acc_nav": "DECIMAL(10, 4) NOT NULL",
                    "daily_return": "DECIMAL(10, 4) NOT NULL",
                    "dividend": "DECIMAL(10, 4)",
                },
                "primary_key": ["code", "nav_date"],
                "foreign_keys": {"code": "funds(code)"},
                "indexes": ["code"],
            },
            "task_history": {
                "fields": {
                    "task_id": "VARCHAR(36) NOT NULL PRIMARY KEY",
                    "name": "VARCHAR(100) NOT NULL",
                    "priority": "INTEGER NOT NULL DEFAULT 0",
                    "status": "VARCHAR(20) NOT NULL",
                    "progress": "INTEGER NOT NULL DEFAULT 0",
                    "result": "TEXT",
                    "error": "TEXT",
                    "start_time": "DATETIME",
                    "end_time": "DATETIME",
                    "timeout": "INTEGER NOT NULL DEFAULT 3600",
                    "created_at": "DATETIME NOT NULL",
                    "updated_at": "DATETIME NOT NULL",
                },
                "indexes": ["name", "status", "created_at"],
            },
        },
    },
    4: {
        "description": "更新基金信息表结构,重构账户相关表名",
        "changes": {
            "new_tables": [],
            "alter_tables": {
                "funds": {
                    "rename_to": "fund",
                    "modify_columns": {"code": "VARCHAR(12) NOT NULL"},
                    "add_columns": {
                        "full_name": "VARCHAR(255)",
                        "issue_date": "DATETIME",
                        "establishment_date": "DATETIME",
                        "establishment_size": "DECIMAL(20, 2)",
                        "custodian": "VARCHAR(100)",
                        "fund_manager": "VARCHAR(100)",
                        "management_fee": "DECIMAL(10, 4)",
                        "custodian_fee": "DECIMAL(10, 4)",
                        "sales_service_fee": "DECIMAL(10, 4)",
                        "tracking": "VARCHAR(100)",
                        "performance_benchmark": "VARCHAR(100)",
                    },
                },
                "accounts": {"rename_to": "account"},
                "portfolios": {
                    "rename_to": "portfolio",
                    "modify_foreign_keys": {"account_id": "account(id)"},
                },
                "fund_transactions": {
                    "modify_columns": {"code": "VARCHAR(12) NOT NULL"},
                    "modify_foreign_keys": {
                        "code": "fund(code)",
                        "portfolio_id": "portfolio(id)",
                    },
                },
                "fund_positions": {
                    "modify_columns": {"code": "VARCHAR(12) NOT NULL"},
                    "modify_foreign_keys": {
                        "code": "fund(code)",
                        "portfolio_id": "portfolio(id)",
                    },
                },
                "fund_nav_history": {
                    "modify_columns": {"code": "VARCHAR(12) NOT NULL"},
                    "modify_foreign_keys": {"code": "fund(code)"},
                },
            },
            "drop_tables": [],
        },
        "schema": {
            # "accounts": {
            #     "fields": {
            #         "id": "VARCHAR(255) NOT NULL PRIMARY KEY",
            #         "created_at": "DATETIME NOT NULL",
            #         "updated_at": "DATETIME NOT NULL",
            #         "name": "VARCHAR(255) NOT NULL",
            #         "description": "VARCHAR(255)",
            #     }
            # },
            # "portfolios": {
            #     "fields": {
            #         "id": "VARCHAR(255) NOT NULL PRIMARY KEY",
            #         "created_at": "DATETIME NOT NULL",
            #         "updated_at": "DATETIME NOT NULL",
            #         "account_id": "VARCHAR(255) NOT NULL",
            #         "name": "VARCHAR(255) NOT NULL",
            #         "description": "VARCHAR(255)",
            #         "is_default": "INTEGER NOT NULL",
            #     },
            #     "foreign_keys": {"account_id": "accounts(id)"},
            #     "indexes": ["account_id"],
            # },
            "account": {
                "fields": {
                    "id": "VARCHAR(255) NOT NULL PRIMARY KEY",
                    "created_at": "DATETIME NOT NULL",
                    "updated_at": "DATETIME NOT NULL",
                    "name": "VARCHAR(255) NOT NULL",
                    "description": "VARCHAR(255)",
                }
            },
            "portfolio": {
                "fields": {
                    "id": "VARCHAR(255) NOT NULL PRIMARY KEY",
                    "created_at": "DATETIME NOT NULL",
                    "updated_at": "DATETIME NOT NULL",
                    "account_id": "VARCHAR(255) NOT NULL",
                    "name": "VARCHAR(255) NOT NULL",
                    "description": "VARCHAR(255)",
                    "is_default": "INTEGER NOT NULL",
                },
                "foreign_keys": {"account_id": "account(id)"},
                "indexes": ["account_id"],
            },
            "fund": {
                "fields": {
                    "code": "VARCHAR(12) NOT NULL PRIMARY KEY",
                    "name": "VARCHAR(100) NOT NULL",
                    "full_name": "VARCHAR(255)",
                    "type": "VARCHAR(20) NOT NULL",
                    "issue_date": "DATE",
                    "establishment_date": "DATE",
                    "establishment_size": "DECIMAL(20, 4)",
                    "company": "VARCHAR(100) NOT NULL",
                    "custodian": "VARCHAR(100)",
                    "fund_manager": "VARCHAR(100)",
                    "management_fee": "DECIMAL(10, 4)",
                    "custodian_fee": "DECIMAL(10, 4)",
                    "sales_service_fee": "DECIMAL(10, 4)",
                    "tracking": "VARCHAR(100)",
                    "performance_benchmark": "VARCHAR(100)",
                    "investment_scope": "TEXT",
                    "investment_target": "TEXT",
                    "investment_philosophy": "TEXT",
                    "investment_strategy": "TEXT",
                    "dividend_policy": "TEXT",
                    "risk_return_characteristics": "TEXT",
                    "data_source": "VARCHAR(20)",
                    "data_source_version": "VARCHAR(20)",
                    "created_at": "DATETIME NOT NULL",
                    "updated_at": "DATETIME NOT NULL",
                }
            },
            "fund_transactions": {
                "fields": {
                    "id": "VARCHAR(255) NOT NULL PRIMARY KEY",
                    "created_at": "DATETIME NOT NULL",
                    "updated_at": "DATETIME NOT NULL",
                    "portfolio_id": "VARCHAR(255) NOT NULL",
                    "code": "VARCHAR(12) NOT NULL",
                    "type": "VARCHAR(20) NOT NULL",
                    "shares": "DECIMAL(20, 4) NOT NULL",
                    "amount": "DECIMAL(20, 2) NOT NULL",
                    "nav": "DECIMAL(10, 4) NOT NULL",
                    "fee": "DECIMAL(10, 2) NOT NULL",
                    "transaction_date": "DATETIME NOT NULL",
                },
                "foreign_keys": {
                    "portfolio_id": "portfolio(id)",
                    "code": "fund(code)",
                },
                "indexes": ["portfolio_id", "code"],
            },
            "fund_positions": {
                "fields": {
                    "id": "VARCHAR(255) NOT NULL PRIMARY KEY",
                    "created_at": "DATETIME NOT NULL",
                    "updated_at": "DATETIME NOT NULL",
                    "portfolio_id": "VARCHAR(255) NOT NULL",
                    "code": "VARCHAR(12) NOT NULL",
                    "shares": "DECIMAL(20, 4) NOT NULL",
                    "nav": "DECIMAL(10, 4) NOT NULL",
                    "market_value": "DECIMAL(20, 2) NOT NULL",
                    "cost": "DECIMAL(20, 2) NOT NULL",
                    "return_rate": "DECIMAL(10, 4) NOT NULL",
                    "purchase_date": "DATETIME NOT NULL",
                },
                "foreign_keys": {
                    "portfolio_id": "portfolio(id)",
                    "code": "fund(code)",
                },
                "indexes": ["portfolio_id", "code"],
            },
            "fund_nav_history": {
                "fields": {
                    "created_at": "DATETIME NOT NULL",
                    "updated_at": "DATETIME NOT NULL",
                    "code": "VARCHAR(12) NOT NULL",
                    "nav_date": "DATETIME NOT NULL",
                    "nav": "DECIMAL(10, 4) NOT NULL",
                    "acc_nav": "DECIMAL(10, 4) NOT NULL",
                    "daily_return": "DECIMAL(10, 4) NOT NULL",
                    "dividend": "DECIMAL(10, 4)",
                },
                "primary_key": ["code", "nav_date"],
                "foreign_keys": {"code": "fund(code)"},
                "indexes": ["code"],
            },
            "task_history": {
                "fields": {
                    "task_id": "VARCHAR(36) NOT NULL PRIMARY KEY",
                    "name": "VARCHAR(100) NOT NULL",
                    "priority": "INTEGER NOT NULL DEFAULT 0",
                    "status": "VARCHAR(20) NOT NULL",
                    "progress": "INTEGER NOT NULL DEFAULT 0",
                    "result": "TEXT",
                    "error": "TEXT",
                    "start_time": "DATETIME",
                    "end_time": "DATETIME",
                    "timeout": "INTEGER NOT NULL DEFAULT 3600",
                    "created_at": "DATETIME NOT NULL",
                    "updated_at": "DATETIME NOT NULL",
                },
                "indexes": ["name", "status", "created_at"],
            },
        },
    },
}
